######################################################
# Copyright (C) 2005-2008 Parallels Software Inc.    #
# All Rights Reserved.                               #
# http://www.parallels.com                           #
######################################################

obj-m := $(DRIVER).o
$(DRIVER)-objs := pvmnet.o

all:
	make -C $(KERNEL_DIR) M=$(PWD)

clean:
	make -C $(KERNEL_DIR) M=$(PWD) clean
	rm -f Module*.symvers

distclean: clean
	rm -f *~
